### ISSUE TITLE
Update to Linux 4.4

### ISSUE THREAD

**Issue by piranna** [outsinre/cjktty-patch#1]
Linux cjktty [has updated](https://github.com/Gentoo-zh/linux-cjktty/commits/4.4-utf8) to upstream 4.4 version, could you update your stripped patch? Also it would be good to collect the patches for different versions of the kernel, similar to how it's done with [musl-cross patches](https://github.com/GregorR/musl-cross/tree/master/patches) for GCC. This will be very helpful for [NodeOS](https://github.com/NodeOS/NodeOS). If you want I could try to do a pull-request for this.

**Comment by outsinre** [comment]
@piranna Yeah, I see that. Currently the 4.0.5 patch fits all kernels up to 4.4 (I am on 4.4.6).

Your suggestion is good. I will merge the request.
